project:
  type: website
  output-dir: docs

website:
  title: "Pine Straw Distribution"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
