project:
  type: website
  output-dir: docs

website:
  title: "Pine Straw Distributors LLC"
  announcement:
    dismissable: false
    content: "For current prices, email us at [sales@pinestrawdistributors.com](mailto:sales@pinestrawdistributors.com) or call 1-800-xxx-xxxx"
    type: success
    position: below-navbar
  navbar:
    logo: img/logo.svg
    left:
      - href: index.qmd
        text: Home
      - href: products.qmd
        text: Products
      - href: customers.qmd
        text: Customers
      - href: employees.qmd
        text: Employees
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    include-after-body: _footer.html
